# Generated by Django 5.0.3 on 2025-06-22 01:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=4, help_text='Porcentaje de comisión (ej: 0.06 para 6%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('monto_minimo', models.DecimalField(decimal_places=2, help_text='Monto mínimo requerido para aplicar esta regla', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regla de Comisión',
                'verbose_name_plural': 'Reglas de Comisión',
                'ordering': ['monto_minimo'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='commission_app.vendedor')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ComisionCalculada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_aplicado', models.DecimalField(decimal_places=4, max_digits=5)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('regla_aplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commission_app.regla')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision_calculada', to='commission_app.venta')),
            ],
            options={
                'verbose_name': 'Comisión Calculada',
                'verbose_name_plural': 'Comisiones Calculadas',
                'ordering': ['-fecha_calculo'],
            },
        ),
    ]
